### ISSUE TITLE
type bat not found

### ISSUE THREAD

**Issue by MikhailMS** [AdamWhittingham/adshell#6]
It seems to me that there is a small bug in the **aliases** file on the line 84
```bash
if ( type bat > /dev/null ) ; then
  alias cat='bat'
fi
```

When you run that on MacOS (10.14.3), it gives you an error
```
-bash: type: bat: not found
```

Nothing serious, but it appears everytime I open up new tab in terminal and it just annoying a bit :)

**Comment by AdamWhittingham** [comment]
Thanks @MikhailMS - sorry this was left open so long, but it was fixed a few months ago. I'd had redirected both streams but it should be silent again now 👌
